{% set name = "xyzservices" %}
{% set version = "2021.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9a9720b294a40e7ccfde09bdba1864c15b970211a4440f5f3147af08139c0d4
  patches:
    # https://github.com/geopandas/xyzservices/pull/97
    - backport_97.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - xyzservices.providers
    - xyzservices
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopandas/xyzservices
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Source of XYZ tiles providers
  description: |
    xyzservices is a lightweight library providing a repository of available XYZ
    services offering raster basemap tiles. The repository is provided via
    Python API and as a compressed JSON file.
  doc_url: https://xyzservices.readthedocs.io/
  dev_url: https://github.com/geopandas/xyzservices

extra:
  recipe-maintainers:
    - martinfleis
