{% set name = "xyzservices" %}
{% set version = "2022.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c58caec48454ed7436b95eb167709f3a5ce91747062a9dbb33bec72f7ca89fe5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - xyzservices.providers
    - xyzservices
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopandas/xyzservices
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Source of XYZ tiles providers
  description: |
    xyzservices is a lightweight library providing a repository of available XYZ
    services offering raster basemap tiles. The repository is provided via
    Python API and as a compressed JSON file.
  doc_url: https://xyzservices.readthedocs.io/
  dev_url: https://github.com/geopandas/xyzservices

extra:
  recipe-maintainers:
    - martinfleis
