{% set name = "xyzservices" %}
{% set version = "2026.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d226866a5d8e9fef337034d8da37a8298f0a1d9d1489b4018e69579eb321fea4

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - wheel
    - setuptools-scm >=6.2
    - toml
  run:
    - python

test:
  source_files:
    - xyzservices/tests
  imports:
    - xyzservices.providers
    - xyzservices
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Skip test_providers.py because of "ModuleNotFoundError: No module named 'mercantile'"
    - pytest -v xyzservices/tests --ignore=xyzservices/tests/test_providers.py

about:
  home: https://github.com/geopandas/xyzservices
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Source of XYZ tiles providers
  description: |
    xyzservices is a lightweight library providing a repository of available XYZ
    services offering raster basemap tiles. The repository is provided via
    Python API and as a compressed JSON file.
  doc_url: https://xyzservices.readthedocs.io/
  dev_url: https://github.com/geopandas/xyzservices

extra:
  recipe-maintainers:
    - martinfleis
